<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <Authors>mrstefangrimm</Authors>
        <PackageId>Futile.Reqnroll.Amp</PackageId>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Description>Additional classes for reqnroll.</Description>
        <PackageProjectUrl>https://github.com/mrstefangrimm/</PackageProjectUrl>
        <RepositoryUrl>https://github.com/mrstefangrimm/</RepositoryUrl>
        <Version>0.0.1-prerelease21</Version>
        <Company />
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Autofac" Version="4.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.5" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.5" />
        <PackageReference Include="Microsoft.Playwright" Version="1.58.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\LICENSE">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
        <None Include="..\..\README.md">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
    </ItemGroup>

</Project>