<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup>
		<Authors>mrstefangrimm</Authors>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Description>Additional classes for reqnroll.</Description>
		<PackageProjectUrl>https://github.com/mrstefangrimm/</PackageProjectUrl>
		<RepositoryUrl>https://github.com/mrstefangrimm/</RepositoryUrl>
		<Version>0.0.1-prerelease01</Version>
		<Company />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.4" />
		<PackageReference Include="Microsoft.Playwright" Version="1.58.0" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\LICENSE">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>

</Project>